name: Build and Release

on:
  push:
    tags:
      - 'v*'
  schedule:
    - cron: '0 0 * * *'  # Run at midnight UTC
  workflow_dispatch:  # Allow manual triggering

permissions:
  contents: write
  packages: write

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            arch: x86_64
          - os: ubuntu-latest
            arch: arm64
          - os: macos-latest
            arch: x86_64
          - os: macos-latest
            arch: arm64
          - os: windows-latest
            arch: x86_64

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Fetch all history for all tags and branches

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install -r requirements.txt

    - name: Build with PyInstaller
      run: pyinstaller ParticlePlayground.spec

    - name: Copy LICENSE files
      run: |
        cp LICENSE dist/
        mkdir -p dist/assets
        cp assets/LICENSE dist/assets/
      shell: bash

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: ParticlePlayground-${{ matrix.os }}-${{ matrix.arch }}
        path: dist/*

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')

    steps:
    - uses: actions/checkout@v3

    - name: Install GitHub CLI
      run: |
        type -p curl >/dev/null || (sudo apt update && sudo apt install curl -y)
        curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg \
        && sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg \
        && echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null \
        && sudo apt update \
        && sudo apt install gh -y

    - name: Check for existing release
      id: check_release
      run: |
        if gh release view ${{ github.ref_name }} &> /dev/null; then
          echo "exists=true" >> $GITHUB_OUTPUT
        else
          echo "exists=false" >> $GITHUB_OUTPUT
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Update existing release
      if: steps.check_release.outputs.exists == 'true'
      run: |
        gh release edit ${{ github.ref_name }} --title "Release ${{ github.ref_name }}" --notes "Updated release for ${{ github.ref_name }}"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Create new release
      if: steps.check_release.outputs.exists != 'true'
      run: |
        gh release create ${{ github.ref_name }} --title "Release ${{ github.ref_name }}" --notes "Release ${{ github.ref_name }}"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - uses: actions/download-artifact@v3
      with:
        path: artifacts

    - name: Remove existing assets and upload new ones
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        # Remove existing assets
        existing_assets=$(gh release view ${{ github.ref_name }} --json assets -q '.assets[].name')
        for asset in $existing_assets; do
          gh release delete-asset ${{ github.ref_name }} "$asset" --yes
        done
        
        # Upload new assets
        for artifact in artifacts/*; do
          find "$artifact" -type f | while read -r file; do
            gh release upload ${{ github.ref_name }} "$file" --clobber
          done
        done

  cleanup:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install GitHub CLI
      run: |
        type -p curl >/dev/null || (sudo apt update && sudo apt install curl -y)
        curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg \
        && sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg \
        && echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null \
        && sudo apt update \
        && sudo apt install gh -y

    - name: Remove invalid releases
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        releases=$(gh release list --limit 1000 || true)
        if [ -n "$releases" ]; then
          echo "$releases" | grep -v "Nightly Build" | awk '{print $1, $3}' | while read -r tag rest; do
            if [[ ! $tag =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
              gh release delete $tag --yes || true
            fi
          done
        else
          echo "No releases found to clean up."
        fi

  nightly:
    needs: [build, cleanup]
    runs-on: ubuntu-latest
    if: github.event_name == 'schedule'

    steps:
    - uses: actions/checkout@v3

    - name: Install GitHub CLI
      run: |
        type -p curl >/dev/null || (sudo apt update && sudo apt install curl -y)
        curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg \
        && sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg \
        && echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null \
        && sudo apt update \
        && sudo apt install gh -y

    - name: Get latest commit hash
      id: get_hash
      run: echo "hash=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT

    - name: Check for existing nightly tag
      id: check_tag
      run: |
        git fetch --tags
        if git rev-parse nightly >/dev/null 2>&1; then
          echo "exists=true" >> $GITHUB_OUTPUT
          echo "current_hash=$(git rev-parse nightly)" >> $GITHUB_OUTPUT
        else
          echo "exists=false" >> $GITHUB_OUTPUT
        fi

    - name: Update or create nightly tag
      if: steps.check_tag.outputs.exists != 'true' || steps.check_tag.outputs.current_hash != steps.get_hash.outputs.hash
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git tag -f nightly
        git push origin nightly -f

    - name: Create or update Nightly Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        if gh release view nightly &> /dev/null; then
          gh release edit nightly --title "Nightly Build" --notes "Updated nightly build"
        else
          gh release create nightly --title "Nightly Build" --notes "Automated nightly build" --prerelease
        fi

    - uses: actions/download-artifact@v3
      with:
        path: artifacts

    - name: Remove existing assets and upload new ones for Nightly
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        # Remove existing assets
        existing_assets=$(gh release view nightly --json assets -q '.assets[].name')
        for asset in $existing_assets; do
          gh release delete-asset nightly "$asset" --yes
        done
        
        # Upload new assets
        for artifact in artifacts/*; do
          find "$artifact" -type f | while read -r file; do
            gh release upload nightly "$file" --clobber
          done
        done